-- Southern Steel — Supabase Schema
-- Run this in your Supabase SQL Editor to set up all tables

-- Leads from chatbot or manual entry
CREATE TABLE leads (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  phone text,
  email text,
  type text,
  material text,
  setting text,
  timeline text,
  scope text,
  zip text,
  score integer DEFAULT 0,
  tier text DEFAULT 'LOW',
  status text DEFAULT 'new',
  photos text[],
  source text DEFAULT 'chatbot',
  estimated_value numeric,
  notes text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Proposals generated by AI
CREATE TABLE proposals (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  lead_id uuid REFERENCES leads(id),
  proposal_number text NOT NULL,
  client_name text NOT NULL,
  client_company text,
  client_email text,
  scope_of_work text,
  line_items jsonb NOT NULL,
  subtotal numeric NOT NULL,
  tax_rate numeric DEFAULT 0.0825,
  tax numeric NOT NULL,
  total numeric NOT NULL,
  terms text DEFAULT '50% deposit to begin. Balance on completion. Valid 30 days. All work guaranteed 1 year.',
  status text DEFAULT 'draft',
  signed_at timestamptz,
  signed_by text,
  ai_generated boolean DEFAULT true,
  generation_time_seconds numeric,
  created_at timestamptz DEFAULT now()
);

-- Jobs in progress
CREATE TABLE jobs (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  proposal_id uuid REFERENCES proposals(id),
  lead_id uuid REFERENCES leads(id),
  client_name text NOT NULL,
  description text,
  value numeric,
  status text DEFAULT 'scheduled',
  progress integer DEFAULT 0,
  start_date date,
  due_date date,
  completed_at timestamptz,
  notes text,
  created_at timestamptz DEFAULT now()
);

-- Company settings
CREATE TABLE company_settings (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  company_name text DEFAULT 'Southern Steel',
  tagline text DEFAULT 'Welding & Fabrication',
  city text DEFAULT 'San Antonio',
  state text DEFAULT 'TX',
  license_number text,
  phone text,
  email text,
  logo_url text,
  default_tax_rate numeric DEFAULT 0.0825
);

-- Insert default company settings
INSERT INTO company_settings (company_name) VALUES ('Southern Steel');

-- Enable Row Level Security (optional, disable for development)
-- ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE proposals ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE jobs ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE company_settings ENABLE ROW LEVEL SECURITY;
